const BLOCKLIST: string[] = [
  "terrorism",
  "terrorist",
  "mass shooting",
  "school shooting",
  "genocide",
  "ethnic cleansing",
  "holocaust",
  "suicide bombing",
  "car bombing",
  "massacre",
  "beheading",
  "beheaded",
  "execution",
  "assassinated",
  "assassination",
  "lynching",
  "lynched",
  "torture",
  "tortured",
  "war crime",
  "war crimes",
  "crimes against humanity",
  "concentration camp",
  "death camp",
  "extermination",
  "rape",
  "sexual assault",
  "child abuse",
  "child murder",
  "serial killer",
  "mass murder",
  "mass murderer",
  "hostage crisis",
  "hostage",
  "kidnapping",
  "abduction",
  "bombing",
  "bombed",
  "plane crash",
  "crashed into",
  "hijacked",
  "hijacking",
  "famine",
  "starvation",
  "nuclear disaster",
  "meltdown",
  "chemical attack",
  "nerve agent",
  "biological weapon",
  "anthrax",
  "plague",
  "pandemic",
  "mass grave",
];

export function isSensitive(text: string): boolean {
  const lower = text.toLowerCase();
  return BLOCKLIST.some((word) => lower.includes(word));
}

export const SENSITIVE_REFRAME =
  "The world was going through its own enormity.";
